### ISSUE TITLE
Script for downloading data

### ISSUE THREAD

**Issue by jasperhyp** [DeepGraphLearning/PEER_Benchmark#1]
Hi,  Tahnks for sharing the code.  Is there a script to download all dataset?

**Comment by ChrisAllenMing** [comment]
Hi, thanks for the interests in our work.

The PEER Benchmark repo is based on TorchDrug v0.2.0. It will automatically download each dataset when you first run a configuration (e.g., [Beta-lactamase prediction with BERT](https://github.com/DeepGraphLearning/PEER_Benchmark/blob/main/config/single_task/BERT/beta_BERT.yaml)), and the dataset will be loaded from cache for future runs.

You can find the link of each dataset in the corresponding dataset class in TorchDrug, e.g., the link of the Beta-lactamase dataset is in [this file](https://github.com/DeepGraphLearning/torchdrug/blob/master/torchdrug/datasets/beta_lactamase.py). We will provide a script to download all PEER benchmark datasets in these weeks.

**Comment by Ming-Qin-tech** [comment]
“We will provide a script to download all PEER benchmark datasets in these weeks.”
Is it finished？

**Comment by j-adamczyk** [comment]
@ChrisAllenMing could you please provide the script to download all datasets?
