### ISSUE TITLE
Is there a timeline for EC and GO be released?

### ISSUE THREAD

**Issue by jasperhyp** [DeepGraphLearning/PEER_Benchmark#4]
I found they are in similar format in your GearNet paper as the other benchmarks.  Will they be released soon?

**Comment by ChrisAllenMing** [comment]
Hi, thanks for the great suggestion. Our next step is to release the codes and configs of three tasks in FLIP: AAV, GB1 and Thermostability. After that, we will benchmark sequence models on EC and GO and release the code.

**Comment by Oxer11** [comment]
Hi! The codes and configs for FLIP has just been released in 465aee1. For sequence models on EC and GO, you can find the configs in https://github.com/DeepGraphLearning/GearNet.

**Comment by jasperhyp** [comment]
Great, thanks for actively maintaining this!

**Comment by jasperhyp** [comment]
Actually, regarding mutation fitness, you might also be interested in `ProteinGym` in [this repo](https://github.com/OATML-Markslab/Tranception).
