### ISSUE TITLE
Transformer Models

### ISSUE THREAD

**Issue by LYZ02** [DeepGraphLearning/PEER_Benchmark#6]
Hi, I found no config file for the transformer model. I can't reproduce the transformer model's result mentioned in the paper.

**Comment by ChrisAllenMing** [comment]
The Transformer model in the paper is denoted as "BERT" in this repo, whose single-task learning configs are stored in this direction: https://github.com/DeepGraphLearning/PEER_Benchmark/tree/main/config/single_task/BERT

**Comment by LYZ02** [comment]
OK, Thank you for your timely reply!
